USE test;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS SPRING_SESSION_ATTRIBUTES;
DROP TABLE IF EXISTS SPRING_SESSION;

CREATE TABLE account (
	account_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	account_user VARCHAR(255) NOT NULL,
	account_password VARCHAR(255) NOT NULL,
	account_block BOOLEAN DEFAULT FALSE,
	account_startdate DATE NOT NULL,
	account_enddate DATE
);

CREATE TABLE comment (
	comment_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	comment_content VARCHAR(1000) NOT NULL,
	account_id INT UNSIGNED NOT NULL,
	datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (account_id) REFERENCES account(account_id)
);
